apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mari
  namespace: mari
spec:
  ingressClassName: nginx
  tls:
    - hosts: [mari.example.com]
      secretName: mari-tls
  rules:
    - host: mari.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
