apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mari
spec:
  selector:
    app.kubernetes.io/name: mari-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mari
spec:
  selector:
    app.kubernetes.io/name: mari-web
  ports:
    - name: http
      port: 80
      targetPort: http
